In [1]:
import numpy as np
import config
import matplotlib
import matplotlib.pyplot as plt
config.conf_matplolib()
#from spharm import Spharmt, getspecindx
from spectral.spherical.transforms import Yslm_vec, SHExpand
from spectral.spherical.grids import GLGrid
#from waveformtools.grids import GLGrid
import h5py
from waveformtools.diagnostics import method_info

/home/vaishakp/Documents/Projects/Codes/waveformtools/waveformtools
No module named 'pycbc'


In [2]:
from config.verbosity import levels
vl = levels()
vl.set_print_verbosity(1)

print verbosity has been set to 1 at /home/vaishakp/Documents/Projects/Codes/config/config/__init__.py


In [3]:
ell_max=14

gl_info = GLGrid(L=ell_max)
theta_grid, phi_grid = gl_info.meshgrid

In [4]:
from spectral.spherical.swsh import Yslm


func = np.sin(theta_grid)
#func = np.ones(gl_info.shape)
#func = Yslm_vec(ell=1, emm=-1, spin_weight=0, theta_grid=theta_grid, phi_grid=phi_grid)

In [5]:
minfo = method_info(ell_max=ell_max, int_method='GL', diff_method='SH', swsh_routine='waveformtools')

In [6]:
help(SHExpand)

Help on function SHExpand in module spectral.spherical.transforms:

SHExpand(func, info, method_info, err_info=False, auto_ell_max=False, res_tol_percent=3, reg=False, reg_order=1)
    Expand a given function in spin weight 0 spherical harmonics
    upto an optimal :math:`\ell \leq \ell_{max}`.
    
    Parameters
    ----------
    func : ndarray
           The function to be expanded.
    info : Grid
           An instance of the Spherical grid class
           that stores the details of the structure
           of a grid on a topological sphere.
    method_info : MethodInfo
                  An instance of the method info
                  class that contains informations
                  about the numerical methods
                  to be used during the following
                  operations.
    err_info : bool
               Whether or not to compute and return
               the error measures related to the
               SH representation.
    
    Returns
    -------
    mo

In [7]:
minfo

In [8]:
minfo.swsh_routine

'waveformtools'

In [24]:
wfmodes = SHExpand(func, gl_info, minfo, err_info=False)

In [10]:
%%timeit
wfmodes = SHExpand(func, gl_info, minfo, err_info=False)

338 ms ± 22.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
wfmodes = SHExpand(func, gl_info, minfo, err_info=True)

In [12]:
gl_info.grid_type

'GL'

In [13]:
%%timeit
wfmodes = SHExpand(func, gl_info, minfo, err_info=True)

5.99 s ± 925 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [13]:
%%timeit
wfmodes = SHExpand(func, gl_info, minfo, err_info=True)

1.92 s ± 107 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
wfmodes.residuals

[0.7191949522280763,
 0.31485649428238877,
 0.31485649428238877,
 0.06425147045912484,
 0.06425147045912484,
 0.025180709942656917,
 0.025180709942656913,
 0.01147385554990485,
 0.01147385554990485,
 0.005198455556385916,
 0.005198455556385916,
 0.0020190549348912943,
 0.0020190549348912943,
 0.00045317737252729474,
 0.00045317737252729474,
 6.999221493841085e-14]

In [11]:
wfmodes.residuals

[0.7191949522280763,
 0.3148564942823888,
 0.3148564942823888,
 0.0642514704591249,
 0.0642514704591249,
 0.02518070994265695,
 0.025180709942656955,
 0.01147385554990487,
 0.01147385554990487,
 0.0051984555563858986,
 0.0051984555563858986,
 0.002019054934891294,
 0.002019054934891294,
 0.0004531773725272877,
 0.0004531773725272877,
 7.004545734781042e-14]

In [15]:
wfmodes.residuals

[0.7191949522280763,
 0.3148564942823888,
 0.3148564942823888,
 0.06425147045912491,
 0.06425147045912491,
 0.02518070994265696,
 0.025180709942656962,
 0.011473855549904875,
 0.011473855549904877,
 0.005198455556385904,
 0.005198455556385904,
 0.0020190549348912995,
 0.0020190549348912995,
 0.00045317737252728997,
 0.0004531773725272899,
 7.004226228157524e-14]

In [10]:
minfo2 = method_info(ell_max=ell_max, int_method='GL', diff_method='SH', swsh_routine='spherepack')

In [11]:
spmodes = SHExpand(func, gl_info, minfo2, err_info=False)

l 0, m0
l 0, m 0, vind 0
l 1, m0
l 1, m 0, vind 2
l 1, m1
l 1, m 1, vind 3
l 1, m -1, vind 1
l 2, m0
l 2, m 0, vind 6
l 2, m1
l 2, m 1, vind 7
l 2, m2
l 2, m 2, vind 8
l 2, m -2, vind 4
l 2, m -1, vind 5
l 3, m0
l 3, m 0, vind 12
l 3, m1
l 3, m 1, vind 13
l 3, m2
l 3, m 2, vind 14
l 3, m3
l 3, m 3, vind 15
l 3, m -3, vind 9
l 3, m -2, vind 10
l 3, m -1, vind 11
l 4, m0
l 4, m 0, vind 20
l 4, m1
l 4, m 1, vind 21
l 4, m2
l 4, m 2, vind 22
l 4, m3
l 4, m 3, vind 23
l 4, m4
l 4, m 4, vind 24
l 4, m -4, vind 16
l 4, m -3, vind 17
l 4, m -2, vind 18
l 4, m -1, vind 19
l 5, m0
l 5, m 0, vind 30
l 5, m1
l 5, m 1, vind 31
l 5, m2
l 5, m 2, vind 32
l 5, m3
l 5, m 3, vind 33
l 5, m4
l 5, m 4, vind 34
l 5, m5
l 5, m 5, vind 35
l 5, m -5, vind 25
l 5, m -4, vind 26
l 5, m -3, vind 27
l 5, m -2, vind 28
l 5, m -1, vind 29
l 6, m0
l 6, m 0, vind 42
l 6, m1
l 6, m 1, vind 43
l 6, m2
l 6, m 2, vind 44
l 6, m3
l 6, m 3, vind 45
l 6, m4
l 6, m 4, vind 46
l 6, m5
l 6, m 5, vind 47
l 6, m6
l 6, m 6, vind 

In [12]:
spmodes.mode(8, 0)

np.complex128(-0.02244383530366422+0j)

In [ ]:
spmodes.mode(8, 0)

(-0.02244383530366422+0j)

In [ ]:
wfmodes.mode(8, 0)

(-0.02244371477198641+0j)

In [ ]:
3.5449077018110318/2.5066284430248484

1.4142134673670463

In [ ]:
np.sqrt(2)

1.4142135623730951

In [ ]:
aaa = np.array([-2, -1, 0, 1, 2])

In [ ]:
aaa[aaa>0]

array([1, 2])

In [13]:
wfmodes.evaluate_old(theta=np.pi/2 , phi=0, ell_max=wfmodes.ell_max)

np.clongdouble('1.0000000000000531427+9.6296497219361792653e-35j')

In [14]:
%%timeit
wfmodes.evaluate_old(theta=np.pi/2 , phi=0, ell_max=wfmodes.ell_max)

12.1 s ± 983 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [16]:
wfmodes.evaluate(theta=np.pi/2 , phi=0, ell_max=wfmodes.ell_max)

array(1.-8.75142567e-31j)

In [12]:
wfmodes.evaluate(theta=theta_grid , phi=phi_grid, ell_max=wfmodes.ell_max).shape

(15, 30)

In [17]:
%%timeit
wfmodes.evaluate(theta=np.pi/2 , phi=0, ell_max=wfmodes.ell_max)

7.05 s ± 865 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
m = 2.0

type(m)

float

In [16]:
if int(m)==m:
    print(1)

1


In [10]:
wfmodes.evaluate_sp(theta=np.pi/2 , phi=0, ell_max=wfmodes.ell_max)

(1.0000000000000526+0j)

In [85]:
from importlib import reload
import spectral
reload(spectral.spherical.swsh)

<module 'spectral.spherical.swsh' from '/home/vaishakprasad/Documents/Projects/Codes/custom_libraries/spectral/spectral/spherical/swsh.py'>

In [86]:
from spectral.spherical.swsh import create_Ylm_modes_array

In [87]:
sYlm = create_Ylm_modes_array(theta=np.pi/2, phi=0.0, ell_max=2, spin_weight=-2)

In [88]:
sYlm.mode(2, 2)

(0.15769578262625997-3.862432708645721e-17j)

In [89]:
Yslm(spin_weight=0, theta=np.pi/2, phi=0, ell=2, emm=2)

(0.3862742020231896+0j)

In [37]:
from importlib import reload
import spectral
reload(spectral.spherical.Yslm_mp)

<module 'spectral.spherical.Yslm_mp' from '/home/vaishakprasad/Documents/Projects/Codes/custom_libraries/spectral/spectral/spherical/Yslm_mp.py'>

In [18]:
from spectral.spherical.Yslm_mp import Yslm_mp

In [19]:
theta_grid

array([[0.15512311, 0.15512311, 0.15512311, 0.15512311, 0.15512311,
        0.15512311, 0.15512311, 0.15512311, 0.15512311, 0.15512311,
        0.15512311, 0.15512311, 0.15512311, 0.15512311, 0.15512311,
        0.15512311, 0.15512311, 0.15512311, 0.15512311, 0.15512311,
        0.15512311, 0.15512311, 0.15512311, 0.15512311, 0.15512311,
        0.15512311, 0.15512311, 0.15512311, 0.15512311, 0.15512311],
       [0.35607183, 0.35607183, 0.35607183, 0.35607183, 0.35607183,
        0.35607183, 0.35607183, 0.35607183, 0.35607183, 0.35607183,
        0.35607183, 0.35607183, 0.35607183, 0.35607183, 0.35607183,
        0.35607183, 0.35607183, 0.35607183, 0.35607183, 0.35607183,
        0.35607183, 0.35607183, 0.35607183, 0.35607183, 0.35607183,
        0.35607183, 0.35607183, 0.35607183, 0.35607183, 0.35607183],
       [0.55820621, 0.55820621, 0.55820621, 0.55820621, 0.55820621,
        0.55820621, 0.55820621, 0.55820621, 0.55820621, 0.55820621,
        0.55820621, 0.55820621, 0.55820621, 0.

In [20]:
cYslm = Yslm_mp(ell_max=14, spin_weight=0, grid_info=gl_info)

In [21]:
cYslm.run()

In [22]:
cYslm.sYlm_modes.mode(2, 2)

array([[ 0.00922067+0.00000000e+00j,  0.0084235 +3.75038362e-03j,
         0.00616983+6.85229184e-03j,  0.00284934+8.76937655e-03j,
        -0.00096382+9.17015639e-03j, -0.00461033+7.98533288e-03j,
        -0.00745968+5.41977277e-03j, -0.00901917+1.91708471e-03j,
        -0.00901917-1.91708471e-03j, -0.00745968-5.41977277e-03j,
        -0.00461033-7.98533288e-03j, -0.00096382-9.17015639e-03j,
         0.00284934-8.76937655e-03j,  0.00616983-6.85229184e-03j,
         0.0084235 -3.75038362e-03j,  0.00922067-2.25841235e-18j,
         0.0084235 +3.75038362e-03j,  0.00616983+6.85229184e-03j,
         0.00284934+8.76937655e-03j, -0.00096382+9.17015639e-03j,
        -0.00461033+7.98533288e-03j, -0.00745968+5.41977277e-03j,
        -0.00901917+1.91708471e-03j, -0.00901917-1.91708471e-03j,
        -0.00745968-5.41977277e-03j, -0.00461033-7.98533288e-03j,
        -0.00096382-9.17015639e-03j,  0.00284934-8.76937655e-03j,
         0.00616983-6.85229184e-03j,  0.0084235 -3.75038362e-03j],
       [ 

In [16]:
%%timeit
cYslm.run()

643 ns ± 8.25 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [34]:
%%timeit
cYslm.run()

1.48 s ± 31.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [53]:
np.array(cYslm.sYlm_modes._modes_data).shape

(225, 15, 30)

In [14]:
%%timeit
cYslm.store_as_modes()

3.84 s ± 73.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [45]:
cYslm.result_list

[[0, array(0.28209479+0.j)],
 [1, array(0.34549415+0.j)],
 [2, array(5.42457759e-17+0.j)],
 [3, array(-0.34549415+0.j)],
 [4, array(0.3862742+0.j)],
 [5, array(1.71540205e-16+0.j)],
 [6, array(-0.31539157+0.j)],
 [7, array(-1.71540205e-16+0.j)],
 [8, array(0.3862742+0.j)]]

In [47]:
wfmodes.mode(1,0)

(2.1236804377400126e-16+0j)

In [50]:
int(np.sqrt(5)-1)

1

In [52]:
int(1.99)

1

In [54]:
int(np.sqrt(5))

2

In [51]:
5- (4)

1

In [55]:
1 - 2

-1

In [21]:
%%timeit
def get_index(ell, emm):
    ind = 0
    for ell_ind in range(ell + 1):
        ind += 2 * ell_ind + 1

    return ind + emm - ell_ind - 1

#info = GLGrid(L=24)
# minfo = method_info(ell_max=24, int_method='GL')

ell_max = 24

#from waveformtools.transforms import Yslm_prec_grid

#theta_grid, phi_grid = info.meshgrid

theta = np.pi/2
phi = 0
spin_weight = 0

import quaternionic, spherical

R = quaternionic.array.from_spherical_coordinates(theta, phi)
# ell_max = ell

wigner = spherical.Wigner(ell_max)

Y2 = wigner.sYlm(spin_weight, R)


Ylm_spherical = Y2.T[get_index(2, 0)].T

313 µs ± 17.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [18]:
Y2.shape

(625,)

In [1]:
import numpy as np

In [3]:
aa = np.zeros((10, *(2, 2)))

In [4]:
aa.shape

(10, 2, 2)

In [54]:
from qlmtools.integration import TwoDIntegral

In [55]:
func = np.sin(theta_grid)

In [56]:
cYslm

NameError: name 'sYlm' is not defined

In [60]:
Ym = np.array(cYslm.sYlm_modes._modes_data)

In [62]:
Ym.shape

(225, 15, 30)

In [63]:
integrand = Ym*func

In [70]:
integrand.shape

(225, 15, 30)

In [67]:
modes_vec = TwoDIntegral(integrand, gl_info, method='GL')

In [69]:
modes_vec.shape

()

In [74]:
np.tensordot(integrand, gl_info.weights_grid, axes=((-2, -1), (0,1))).shape

(225,)

In [15]:
class trial:

    def __init__(self, a):
        self.a = a

    b = 0

In [22]:
tt = trial(1)
tt2 = trial(2)

In [23]:
tt.a

1

In [24]:
tt.b

0

In [19]:
tt.b = 3

In [1]:
import numpy as np
import numba as nb

In [6]:
nb.typeof([2.0, 3.4])

List(float64, True)

In [9]:
nb.typeof([[2, [1, 2, 3], [0, [1, 2]]]])

List(reflected list(int64)<iv=None>, True)

In [10]:
nb.typeof({'l0': {'m1' : 4.2}})

ValueError: Cannot determine Numba type of <class 'dict'>